[package]
name = "into_map_demo"
version = "0.1.0"
authors = ["Rahul Sharma <creativcoders@gmail.com>"]
edition = "2018"

[dependencies]
into_map = { path = "into_map" }
into_map_derive = { path = "into_map_derive" }
