@startuml
actor user
participant pkjs [
    =Polkadot-JS Rococo app
    ----
    [[https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer 波卡洛可可前端]]
]
participant browser[
    =浏览器
    ----
    浏览器做其他申请操作
]
participant terminal [
    =终端
    ----
    用于检查和编译
]
== Set up a wallet ==
browser -> browser: connect & have an account
user -> user: backup & make note
note left
Back up your secret seed phrase.

Make note of your accountID that is
using the default 42 SS58 prefix for
use with Rococo.
end note
browser -> browser: acquire ROC in [[https://matrix.to/#/#rococo-faucet:matrix.org Rococo faucet matrix channel]]
== Acquire a ParaID ==
pkjs -> pkjs: Network >> Parathreads\nReserve a unique ParaID
note left: Make note of this
note right
请注意，在 Rococo 上，
ParaID 编号 0-999 保留给[[https://wiki.polkadot.network/docs/learn-common-goods#system-level-chains 系统平行链]],
而 1000-1999 保留给[[https://wiki.polkadot.network/docs/learn-common-goods#public-utility-chains 公用工具平行链]].

只有尚未保留的 2000 及以上数字才能用于社区平行链。
end note
terminal -> terminal: generate parachain genesis and wasm files
note left
注册平行链所需的文件必须明确指定正确的中继链和正确的 ParaID。

在本教程中，中继链是 rococo，而不是 Connect a local parachain
教程中使用的 rococo-local。

配置您的链规范以使用：
1. 你的Rococo ParaID。
2. 您的整理者节点的开发密钥和帐户的独特替代方案。
虽然 Alice 和此类帐户可以使用，但您绝对不应该使用它们！
3. 为洛可可生成适当的平行链创世状态。
4. 为 Rococo 生成平行链运行时 Wasm blob。
end note
terminal -> terminal: start your collator
note left
对于嵌入式中继链和平行链，您必须拥有可公开访问
和发现的整理者对等端口。这样你就可以与洛可可验证
节点对等，否则你将无法产生区块！

对等端口使用 --port <collator node>--
--port <relay node>这两个 CLI 标志设置，
请务必分别对两个节点执行此操作

您很可能至少希望您的collator的 --ws-port <ws port>
端口也打开，以允许您自己（和其他人）通过 Polkadot
应用程序 UI 或 API 调用与其连接。
end note
pkjs -> pkjs: Register as a parathread
browser -> browser: 申请开通你的平行链插槽
note over of browser
在平行链作为平行线程激活后，相关项目团队应在
Rococo 上[[https://github.com/paritytech/subport/issues/new?assignees=&labels=Rococo&template=rococo.yaml 打开永久或临时平行链插槽的请求]]。

Rococo 运行时需要 sudo 访问权限来分配槽
(AssignSlotOrigin = EnsureRoot<Self::AccountId>;)。

Rococo sudo 密钥目前由 Parity Technologies 控制，
因此要进行获取插槽所需的操作，请在完成上述操作并准备好
连接后转到 Subport repo 并打开 Rococo Slot Request！
激活您的插槽后，Parity 团队成员将做出回应。

最终，该过程旨在通过洛可可式治理框架由社区驱动。
end note
note left
永久插槽是分配给当前在 Polkadot 上拥有平行链插槽的团队
（在成功的插槽租赁拍卖之后）的平行链插槽，因此需要不断测
试他们的代码库以与现实世界中的最新前沿功能兼容（洛可可）。

只有有限数量的永久插槽可用
end note
note right
临时插槽是平行链插槽，以连续的循环方式动态分配。

在每个租期开始时，一定数量的平行线程（最多为中继
链配置中定义的最大值）会在一定时间内自动升级为平
行链。在租约结束期间处于活动状态的平行链会自动降
级为平行线程，以释放插槽供其他人在后续期间使用。

临时插槽旨在供尚未在 Polkadot 上拥有平行链插
槽的团队使用，并计划在不久的将来使用。
end note
pkjs -> pkjs: assign a temporary slot
note left
1. Open Polkadot-JS Apps for Rococo.
2. Click Developer > Extrinsics.
3. Select the account you want to use to submit the transaction.
4. Select the assignedSlots pallet .
5. Choose the assignTempParachainSlot function.
6. Insert your reserved ParaID.
Make sure you use the ParaID you previously reserved.
7. Select Current for the LeasePeriodStart.
If the current slot is full, you will be assigned the next available slot.
8. Sign and submit the transaction.
end note
note right
给定 1 天的租期，洛可可分配的平行链插槽的当前设置是（在撰写本文时）：
1. 永久插槽最短持续时间：1 年（365 天）
2. 临时时段最短持续时间：3 天
3. 永久插槽的最大数量：最多 25 个永久插槽
4. 最大临时槽数：最多 20 个临时槽
5. 每个租期分配的最大临时时段：每 3 天临时租期最多 5 个临时时段
end note
== Congratulations! ==
note over of pkjs
Parity 团队激活您的插槽后，您可以在 Rococo 测试网络上测试您的平行链。

请注意，当您的临时插槽租约结束时，平行链会自动降级为平行线程。
注册和批准的插槽以循环方式自动循环，因此您可以不时作为平行链重新上线。
end note
@enduml