@startmindmap
scale 850 width
* Substrate Tutorials
** Get started
*** Build a local blockchain
*** Simulate a network
*** Add trusted nodes
*** Authorize specific nodes
*** monitor node metrics
*** Upgrade a running network
** Work with pallets
*** Add a pallet to the runtime
*** Configure the contracts pallet
*** Use macros in a custom pallet
** Develop smart contracts
*** Prepare your first contract
*** Develop a smart contract
*** Use maps for storing values
*** Buid a token contract
*** Troubleshoot smart contracts
** Connect with other chains
*** Start a local relay chain
*** Connect a local parachian
*** Connect to Rococo testnet
*** Access EVM accounts
@endmindmap