[package]
name = "callrust"
version = "0.1.0"
authors = ["blackanger <blackanger.z@gmail.com>"]
edition = "2018"

[dependencies]
libc="0.2.43"
[lib]
name = "callrust"
crate-type = ["staticlib", "cdylib"]
