@startmindmap
* [[https://github.com/paritytech/substrate/blob/master/Cargo.toml master/Cargo.toml]]
** bin
*** node-template
**** docs
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/node/Cargo.toml node/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/template/Cargo.toml template/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/Cargo.toml runtime/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/tree/master/bin/node-template/node-template/scripts node-template/scripts]]
*** node
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/bench/Cargo.toml bench/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/Cargo.toml cli/Cargo.toml]]
***** benches
***** bin
***** doc
***** res
***** src
***** tests
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/Cargo.toml executor/Cargo.toml]]
***** benches
***** src
***** tests
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/inspect/Cargo.toml inspect/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/primitives/Cargo.toml primitives/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/rpc/Cargo.toml rpc/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/runtime/Cargo.toml runtime/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/testing/Cargo.toml testing/Cargo.toml]]
*** utils
**** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder/Cargo.toml chain-spec-builder/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/Cargo.toml subkey/Cargo.toml]]
** client
*** [[https://github.com/paritytech/substrate/blob/master/client/allocator/Cargo.toml allocator/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/api/Cargo.toml api/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/authority-discovery/Cargo.toml authority-discovery/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/authority-discovery/build.rs authority-discovery/build.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/client/basic-authorship/Cargo.toml basic-authorship/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/beefy/Cargo.toml beefy/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/beefy/rpc/Cargo.toml rpc/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/block-builder/Cargo.toml block-builder/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/chain-spec/Cargo.toml chain-spec/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/chain-spec/derive/Cargo.toml derive/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/cli/Cargo.toml cli/Cargo.toml]]
*** consensus
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/aura/Cargo.toml aura/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/babe/Cargo.toml babe/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/common/Cargo.toml common/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/epochs/Cargo.toml epochs/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/manual-seal/Cargo.toml manual-seal/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/pow/Cargo.toml pow/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/slots/Cargo.toml slots/Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/client/consensus/slots/build.rs slots/build.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/client/consensus/uncles/Cargo.toml uncles/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/db/Cargo.toml db/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/executor/Cargo.toml executor/Cargo.toml]]
**** benches
**** [[https://github.com/paritytech/substrate/blob/master/client/executor/common/Cargo.toml common/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/executor/runtime-test/Cargo.toml runtime-test/Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/client/executor/runtime-test/build.rs runtime-test/build.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/client/executor/wasmi/Cargo.toml wasmi/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/executor/wasmtime/Cargo.toml wasmtime/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/tree/master/client/executor/src/integration_tests src/integration_tests]]
*** [[https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/Cargo.toml finality-grandpa/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/finality-grandpa/rpc/Cargo.toml rpc/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/informant/Cargo.toml informant/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/keystore/Cargo.toml keystore/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/network-gossip/Cargo.toml network-gossip/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/network/Cargo.toml network/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/network/common/Cargo.toml common/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/network/light/Cargo.toml light/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/network/sync/Cargo.toml sync/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/network/test/Cargo.toml test/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/network/build.rs network/build.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/client/offchain/Cargo.toml offchain/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/peerset/Cargo.toml peerset/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/proposer-metrics/Cargo.toml proposer-metrics/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/rpc-api/Cargo.toml rpc-api/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/author src/author]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/chain src/chain]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/child_state src/child_state]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/dev src/dev]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/offchain src/offchain]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/state src/state]]
**** [[https://github.com/paritytech/substrate/tree/master/client/rpc-api/src/system src/system]]
*** [[https://github.com/paritytech/substrate/blob/master/client/rpc-servers/Cargo.toml rpc-servers/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/rpc/Cargo.toml rpc/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/service/Cargo.toml service/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/tree/master/client/service/src/chain_ops src/chain_ops]]
**** [[https://github.com/paritytech/substrate/tree/master/client/service/src/client src/client]]
**** [[https://github.com/paritytech/substrate/tree/master/client/service/src/task_manager src/task_manager]]
*** [[https://github.com/paritytech/substrate/blob/master/client/state-db/Cargo.toml state-db/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/sync-state-rpc/Cargo.toml sync-state-rpc/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/sysinfo/Cargo.toml sysinfo/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/sysinfo/build.rs sysinfo/build.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/client/telemetry/Cargo.toml telemetry/Cargo.toml]]
*** [[https://github.com/paritytech/substrate/blob/master/client/tracing/Cargo.toml tracing/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/tracing/benches/bench.rs benches/bench.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/client/tracing/proc-macro/Cargo.toml proc-macro/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/tracing/src/block/mod.rs block/mod.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/client/tracing/src/logging/mod.rs logging/mod.rs]]
***** [[https://github.com/paritytech/substrate/blob/master/client/tracing/src/logging/layers/mod.rs layers/mod.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/client/transaction-pool/Cargo.toml transaction-pool/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/transaction-pool/api/Cargo.toml api/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/transaction-pool/benches/basics.rs benches/basics.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/client/transaction-pool/src/lib.rs src/lib.rs]]
***** [[https://github.com/paritytech/substrate/blob/master/client/transaction-pool/src/graph/mod.rs graph/mod.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/client/utils/Cargo.toml utils/Cargo.toml]]
**** [[https://github.com/paritytech/substrate/blob/master/client/utils/src/lib.rs src/lib.rs]]
**** [[https://github.com/paritytech/substrate/tree/master/client/utils/src/notification src/notification]]
**** [[https://github.com/paritytech/substrate/tree/master/client/utils/src/pubsub src/pubsub]]
** docker
*** [[https://github.com/paritytech/substrate/blob/master/docker/README.md docker/README.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docker/build.sh docker/build.sh]]
*** [[https://github.com/paritytech/substrate/blob/master/docker/substrate_builder.Dockerfile docker/substrate_builder.Dockerfile]]
** docs
*** [[https://github.com/paritytech/substrate/blob/master/docs/CHANGELOG.md docs/CHANGELOG.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/Upgrading-2.0-to-3.0.md docs/Upgrading-2.0-to-3.0.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/CODEOWNERS docs/CODEOWNERS]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/CODE_OF_CONDUCT.md docs/CODE_OF_CONDUCT.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/CONTRIBUTING.adoc docs/CONTRIBUTING.adoc]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/PULL_REQUEST_TEMPLATE.md docs/PULL_REQUEST_TEMPLATE.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/README.adoc docs/README.adoc]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/STYLE_GUIDE.md docs/STYLE_GUIDE.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/Structure.adoc docs/Structure.adoc]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/node-template-release.md docs/node-template-release.md]]
*** [[https://github.com/paritytech/substrate/blob/master/docs/rustdocs-release.md docs/rustdocs-release.md]]
** frame
** primitives
** scripts
** test-utils
** utils
@endmindmap