@startmindmap
* substrate/bin
** [[https://github.com/paritytech/substrate/blob/master/bin bin]]
*** [[https://github.com/paritytech/substrate/blob/master/bin/node node]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/bench bench]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/bench/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/bench/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/bench/src/main.rs main.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli cli]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/benches benches]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/bin bin]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/bin/main.rs main.rs]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/doc doc]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/res res]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/src/lib.rs lib.rs]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/cli/tests tests]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor executor]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/benches benches]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/src/lib.rs lib.rs]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/executor/tests tests]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/inspect inspect]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/inspect/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/inspect/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/inspect/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/primitives primitives]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/primitives/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/primitives/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/primitives/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/rpc rpc]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/rpc/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/rpc/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/rpc/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/runtime runtime]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/runtime/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/runtime/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node/testing testing]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/testing/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node/testing/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node/testing/src/lib.rs lib.rs]]
*** [[https://github.com/paritytech/substrate/blob/master/bin/node-template node-template]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/LICENSE LICENSE]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/README.md README.md]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/docs docs]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/docs/rust-setup.md rust-setup.md]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/node node]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/node/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src/main.rs main.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets pallets]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets/template template]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets/template/Cargo.toml Cargo.toml]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets/template/README.md README.md]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets/template/src src]]
******* [[https://github.com/paritytech/substrate/blob/master/bin/node-template/pallets/template/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime runtime]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/runtime/src/lib.rs lib.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/node-template/scripts scripts]]
*** [[https://github.com/paritytech/substrate/blob/master/bin/utils utils]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder chain-spec-builder]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder/README.md README.md]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/utils/chain-spec-builder/src/main.rs main.rs]]
**** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey subkey]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/Cargo.toml Cargo.toml]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/README.md README.md]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/SECURITY.md SECURITY.md]]
***** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/src src]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/src/lib.rs lib.rs]]
****** [[https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/src/main.rs main.rs]]
@endmindmap